# Generated by Django 4.0 on 2022-03-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='finance',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField()),
                ('title', models.TextField(max_length=200)),
                ('body', models.TextField(max_length=200)),
            ],
        ),
    ]
